# .streamlit/secrets.toml
openai_api_key = "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"

