# .streamlit/secrets.toml
openai_api_key = "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"

